services:
  mysqldb:
    image: mysql:8.0.32
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: yyx
      MYSQL_PASSWORD: 123456Aa@
      MYSQL_ROOT_HOST: '%'
  vote-backend:
    image: vote-backend
    build:
      context: ../vote
      dockerfile: dev.Dockerfile
    container_name: vote-backend
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3307/vote
    depends_on:
      - vote-mysqldb
  vote-frontend:
    image: vote-frontend
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: vote-frontend
    environment:
      - VITE_BACKEND_URL=http://vote-backend:8080/api/v1
    depends_on:
      - vote-backend
  nginx:
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3001:80
    container_name: reverse
    depends_on:
      - vote-frontend
      - vote-backend
# todo test compose